INSERT INTO Areas (GovernorateId,NameAr,NameEn,IsActive,CreatedOn) VALUES
/* Start Cairo ID:1 */
(1,N'15 مايو', '15 May',1,GETDATE()),
(1,N'الازبكية', 'Al Azbakeyah',1,GETDATE()),
(1,N'البساتين', 'Al Basatin',1,GETDATE()),
(1,N'التبين', 'Tebin',1,GETDATE()),
(1,N'الخليفة', 'El-Khalifa',1,GETDATE()),
(1,N'الدراسة', 'El darrasa',1,GETDATE()),
(1,N'الدرب الاحمر', 'Aldarb Alahmar',1,GETDATE()),
(1,N'الزاوية الحمراء', 'Zawya al-Hamra',1,GETDATE()),
(1,N'الزيتون', 'El-Zaytoun',1,GETDATE()),
(1,N'الساحل', 'Sahel',1,GETDATE()),
(1,N'السلام', 'El Salam',1,GETDATE()),
(1,N'السيدة زينب', 'Sayeda Zeinab',1,GETDATE()),
(1,N'الشرابية', 'El Sharabeya',1,GETDATE()),
(1,N'مدينة الشروق', 'Shorouk',1,GETDATE()),
(1,N'الظاهر', 'El Daher',1,GETDATE()),
(1,N'العتبة', 'Ataba',1,GETDATE()),
(1,N'القاهرة الجديدة', 'New Cairo',1,GETDATE()),
(1,N'المرج', 'El Marg',1,GETDATE()),
(1,N'عزبة النخل', 'Ezbet el Nakhl',1,GETDATE()),
(1,N'المطرية', 'Matareya',1,GETDATE()),
(1,N'المعادى', 'Maadi',1,GETDATE()),
(1,N'المعصرة', 'Maasara',1,GETDATE()),
(1,N'المقطم', 'Mokattam',1,GETDATE()),
(1,N'المنيل', 'Manyal',1,GETDATE()),
(1,N'الموسكى', 'Mosky',1,GETDATE()),
(1,N'النزهة', 'Nozha',1,GETDATE()),
(1,N'الوايلى', 'Waily',1,GETDATE()),
(1,N'باب الشعرية', 'Bab al-Shereia',1,GETDATE()),
(1,N'بولاق', 'Bolaq',1,GETDATE()),
(1,N'جاردن سيتى', 'Garden City',1,GETDATE()),
(1,N'حدائق القبة', 'Hadayek El-Kobba',1,GETDATE()),
(1,N'حلوان', 'Helwan',1,GETDATE()),
(1,N'دار السلام', 'Dar Al Salam',1,GETDATE()),
(1,N'شبرا', 'Shubra',1,GETDATE()),
(1,N'طره', 'Tura',1,GETDATE()),
(1,N'عابدين', 'Abdeen',1,GETDATE()),
(1,N'عباسية', 'Abaseya',1,GETDATE()),
(1,N'عين شمس', 'Ain Shams',1,GETDATE()),
(1,N'مدينة نصر', 'Nasr City',1,GETDATE()),
(1,N'مصر الجديدة', 'New Heliopolis',1,GETDATE()),
(1,N'مصر القديمة', 'Masr Al Qadima',1,GETDATE()),
(1,N'منشية ناصر', 'Mansheya Nasir',1,GETDATE()),
(1,N'مدينة بدر', 'Badr City',1,GETDATE()),
(1,N'مدينة العبور', 'Obour City',1,GETDATE()),
(1,N'وسط البلد', 'Cairo Downtown',1,GETDATE()),
(1,N'الزمالك', 'Zamalek',1,GETDATE()),
(1,N'قصر النيل', 'Kasr El Nile',1,GETDATE()),
(1,N'الرحاب', 'Rehab',1,GETDATE()),
(1,N'القطامية', 'Katameya',1,GETDATE()),
(1,N'مدينتي', 'Madinty',1,GETDATE()),
(1,N'روض الفرج', 'Rod Alfarag',1,GETDATE()),
(1,N'شيراتون', 'Sheraton',1,GETDATE()),
(1,N'الجمالية', 'El-Gamaleya',1,GETDATE()),
(1,N'العاشر من رمضان', '10th of Ramadan City',1,GETDATE()),
(1,N'الحلمية', 'Helmeyat Alzaytoun',1,GETDATE()),
(1,N'النزهة الجديدة', 'New Nozha',1,GETDATE()),
(1,N'العاصمة الإدارية', 'Capital New',1,GETDATE()),
/* End Cairo ID:1 */

/* Start Giza ID:2 */
(2,N'الجيزة', 'Giza',1,GETDATE()),
(2,N'السادس من أكتوبر', 'Sixth of October',1,GETDATE()),
(2,N'الشيخ زايد', 'Cheikh Zayed',1,GETDATE()),
(2,N'الحوامدية', 'Hawamdiyah',1,GETDATE()),
(2,N'البدرشين', 'Al Badrasheen',1,GETDATE()),
(2,N'الصف', 'Saf',1,GETDATE()),
(2,N'أطفيح', 'Atfih',1,GETDATE()),
(2,N'العياط', 'Al Ayat',1,GETDATE()),
(2,N'الباويطي', 'Al-Bawaiti',1,GETDATE()),
(2,N'منشأة القناطر', 'ManshiyetAl Qanater',1,GETDATE()),
(2,N'أوسيم', 'Oaseem',1,GETDATE()),
(2,N'كرداسة', 'Kerdasa',1,GETDATE()),
(2,N'أبو النمرس', 'Abu Nomros',1,GETDATE()),
(2,N'كفر غطاطي', 'Kafr Ghati',1,GETDATE()),
(2,N'منشأة البكاري', 'Manshiyet Al Bakari',1,GETDATE()),
(2,N'الدقى', 'Dokki',1,GETDATE()),
(2,N'العجوزة', 'Agouza',1,GETDATE()),
(2,N'الهرم', 'Haram',1,GETDATE()),
(2,N'الوراق', 'Warraq',1,GETDATE()),
(2,N'امبابة', 'Imbaba',1,GETDATE()),
(2,N'بولاق الدكرور', 'Boulaq Dakrour',1,GETDATE()),
(2,N'الواحات البحرية', 'Al Wahat Al Baharia',1,GETDATE()),
(2,N'العمرانية', 'Omraneya',1,GETDATE()),
(2,N'المنيب', 'Moneeb',1,GETDATE()),
(2,N'بين السرايات', 'Bin Alsarayat',1,GETDATE()),
(2,N'الكيت كات', 'Kit Kat',1,GETDATE()),
(2,N'المهندسين', 'Mohandessin',1,GETDATE()),
(2,N'فيصل', 'Faisal',1,GETDATE()),
(2,N'أبو رواش', 'Abu Rawash',1,GETDATE()),
(2,N'حدائق الأهرام', 'Hadayek Alahram',1,GETDATE()),
(2,N'الحرانية', 'Haraneya',1,GETDATE()),
(2,N'حدائق اكتوبر', 'Hadayek October',1,GETDATE()),
(2,N'صفط اللبن', 'Saft Allaban',1,GETDATE()),
(2,N'القرية الذكية', 'Smart Village',1,GETDATE()),
(2,N'ارض اللواء', 'Ard Ellwaa',1,GETDATE()),
/* End Giza ID:2 */

/* Start Alexandria ID:3 */
(3,N'ابو قير', 'Abu Qir',1,GETDATE()),
(3,N'الابراهيمية', 'Al Ibrahimeyah',1,GETDATE()),
(3,N'الأزاريطة', 'Azarita',1,GETDATE()),
(3,N'الانفوشى', 'Anfoushi',1,GETDATE()),
(3,N'الدخيلة', 'Dekheila',1,GETDATE()),
(3,N'السيوف', 'El Soyof',1,GETDATE()),
(3,N'العامرية', 'Ameria',1,GETDATE()),
(3,N'اللبان', 'El Labban',1,GETDATE()),
(3,N'المفروزة', 'Al Mafrouza',1,GETDATE()),
(3,N'المنتزه', 'El Montaza',1,GETDATE()),
(3,N'المنشية', 'Mansheya',1,GETDATE()),
(3,N'الناصرية', 'Naseria',1,GETDATE()),
(3,N'امبروزو', 'Ambrozo',1,GETDATE()),
(3,N'باب شرق', 'Bab Sharq',1,GETDATE()),
(3,N'برج العرب', 'Bourj Alarab',1,GETDATE()),
(3,N'ستانلى', 'Stanley',1,GETDATE()),
(3,N'سموحة', 'Smouha',1,GETDATE()),
(3,N'سيدى بشر', 'Sidi Bishr',1,GETDATE()),
(3,N'شدس', 'Shads',1,GETDATE()),
(3,N'غيط العنب', 'Gheet Alenab',1,GETDATE()),
(3,N'فلمينج', 'Fleming',1,GETDATE()),
(3,N'فيكتوريا', 'Victoria',1,GETDATE()),
(3,N'كامب شيزار', 'Camp Shizar',1,GETDATE()),
(3,N'كرموز', 'Karmooz',1,GETDATE()),
(3,N'محطة الرمل', 'Mahta Alraml',1,GETDATE()),
(3,N'مينا البصل', 'Mina El-Basal',1,GETDATE()),
(3,N'العصافرة', 'Asafra',1,GETDATE()),
(3,N'العجمي', 'Agamy',1,GETDATE()),
(3,N'بكوس', 'Bakos',1,GETDATE()),
(3,N'بولكلي', 'Boulkly',1,GETDATE()),
(3,N'كليوباترا', 'Cleopatra',1,GETDATE()),
(3,N'جليم', 'Glim',1,GETDATE()),
(3,N'المعمورة', 'Al Mamurah',1,GETDATE()),
(3,N'المندرة', 'Al Mandara',1,GETDATE()),
(3,N'محرم بك', 'Moharam Bek',1,GETDATE()),
(3,N'الشاطبي', 'Elshatby',1,GETDATE()),
(3,N'سيدي جابر', 'Sidi Gaber',1,GETDATE()),
(3,N'الساحل الشمالي', 'North Coast/sahel',1,GETDATE()),
(3,N'الحضرة', 'Alhadra',1,GETDATE()),
(3,N'العطارين', 'Alattarin',1,GETDATE()),
(3,N'سيدي كرير', 'Sidi Kerir',1,GETDATE()),
(3,N'الجمرك', 'Elgomrok',1,GETDATE()),
(3,N'المكس', 'Al Max',1,GETDATE()),
(3,N'مارينا', 'Marina',1,GETDATE()),
/* End Alexandria ID:3 */

/* Start Dakahlia ID:4 */
(4,N'المنصورة', 'Mansoura',1,GETDATE()),
(4,N'طلخا', 'Talkha',1,GETDATE()),
(4,N'ميت غمر', 'Mitt Ghamr',1,GETDATE()),
(4,N'دكرنس', 'Dekernes',1,GETDATE()),
(4,N'أجا', 'Aga',1,GETDATE()),
(4,N'منية النصر', 'Menia El Nasr',1,GETDATE()),
(4,N'السنبلاوين', 'Sinbillawin',1,GETDATE()),
(4,N'الكردي', 'El Kurdi',1,GETDATE()),
(4,N'بني عبيد', 'Bani Ubaid',1,GETDATE()),
(4,N'المنزلة', 'Al Manzala',1,GETDATE()),
(4,N'تمي الأمديد', 'tami al amdid',1,GETDATE()),
(4,N'الجمالية', 'aljamalia',1,GETDATE()),
(4,N'شربين', 'Sherbin',1,GETDATE()),
(4,N'المطرية', 'Mataria',1,GETDATE()),
(4,N'بلقاس', 'Belqas',1,GETDATE()),
(4,N'ميت سلسيل', 'Meet Salsil',1,GETDATE()),
(4,N'جمصة', 'Gamasa',1,GETDATE()),
(4,N'محلة دمنة', 'Mahalat Damana',1,GETDATE()),
(4,N'نبروه', 'Nabroh',1,GETDATE()),
/* End Dakahlia ID:4 */

/* Start Red Sea ID:5 */
(5,N'الغردقة', 'Hurghada',1,GETDATE()),
(5,N'رأس غارب', 'Ras Ghareb',1,GETDATE()),
(5,N'سفاجا', 'Safaga',1,GETDATE()),
(5,N'القصير', 'El Qusiar',1,GETDATE()),
(5,N'مرسى علم', 'Marsa Alam',1,GETDATE()),
(5,N'الشلاتين', 'Shalatin',1,GETDATE()),
(5,N'حلايب', 'Halaib',1,GETDATE()),
(5,N'الدهار', 'Aldahar',1,GETDATE()),
/* End Red Sea ID:5 */

/* Start Beheira ID:6 */
(6,N'دمنهور', 'Damanhour',1,GETDATE()),
(6,N'كفر الدوار', 'Kafr El Dawar',1,GETDATE()),
(6,N'رشيد', 'Rashid',1,GETDATE()),
(6,N'إدكو', 'Edco',1,GETDATE()),
(6,N'أبو المطامير', 'Abu al-Matamir',1,GETDATE()),
(6,N'أبو حمص', 'Abu Homs',1,GETDATE()),
(6,N'الدلنجات', 'Delengat',1,GETDATE()),
(6,N'المحمودية', 'Mahmoudiyah',1,GETDATE()),
(6,N'الرحمانية', 'Rahmaniyah',1,GETDATE()),
(6,N'إيتاي البارود', 'Itai Baroud',1,GETDATE()),
(6,N'حوش عيسى', 'Housh Eissa',1,GETDATE()),
(6,N'شبراخيت', 'Shubrakhit',1,GETDATE()),
(6,N'كوم حمادة', 'Kom Hamada',1,GETDATE()),
(6,N'بدر', 'Badr',1,GETDATE()),
(6,N'وادي النطرون', 'Wadi Natrun',1,GETDATE()),
(6,N'النوبارية الجديدة', 'New Nubaria',1,GETDATE()),
(6,N'النوبارية', 'Alnoubareya',1,GETDATE()),
/* End Beheira ID:6 */

/* Start Fayoum ID:7 */
(7,N'الفيوم', 'Fayoum',1,GETDATE()),
(7,N'الفيوم الجديدة', 'Fayoum El Gedida',1,GETDATE()),
(7,N'طامية', 'Tamiya',1,GETDATE()),
(7,N'سنورس', 'Snores',1,GETDATE()),
(7,N'إطسا', 'Etsa',1,GETDATE()),
(7,N'إبشواي', 'Epschway',1,GETDATE()),
(7,N'يوسف الصديق', 'Yusuf El Sediaq',1,GETDATE()),
(7,N'الحادقة', 'Hadqa',1,GETDATE()),
(7,N'اطسا', 'Atsa',1,GETDATE()),
(7,N'الجامعة', 'Algamaa',1,GETDATE()),
(7,N'السيالة', 'Sayala',1,GETDATE()),
/* End Fayoum ID:7 */

/* Start Gharbia ID:8 */
(8,N'طنطا', 'Tanta',1,GETDATE()),
(8,N'المحلة الكبرى', 'Al Mahalla Al Kobra',1,GETDATE()),
(8,N'كفر الزيات', 'Kafr El Zayat',1,GETDATE()),
(8,N'زفتى', 'Zefta',1,GETDATE()),
(8,N'السنطة', 'El Santa',1,GETDATE()),
(8,N'قطور', 'Qutour',1,GETDATE()),
(8,N'بسيون', 'Basion',1,GETDATE()),
(8,N'سمنود', 'Samannoud',1,GETDATE()),
/* End Gharbia ID:8 */

/* Start Ismailia ID:9 */
(9,N'الإسماعيلية', 'Ismailia',1,GETDATE()),
(9,N'فايد', 'Fayed',1,GETDATE()),
(9,N'القنطرة شرق', 'Qantara Sharq',1,GETDATE()),
(9,N'القنطرة غرب', 'Qantara Gharb',1,GETDATE()),
(9,N'التل الكبير', 'El Tal El Kabier',1,GETDATE()),
(9,N'أبو صوير', 'Abu Sawir',1,GETDATE()),
(9,N'القصاصين الجديدة', 'Kasasien El Gedida',1,GETDATE()),
(9,N'نفيشة', 'Nefesha',1,GETDATE()),
(9,N'الشيخ زايد', 'Sheikh Zayed',1,GETDATE()),
/* End Ismailia ID:9 */

/* Start Monufya ID:10 */
(10,N'شبين الكوم', 'Shbeen El Koom',1,GETDATE()),
(10,N'مدينة السادات', 'Sadat City',1,GETDATE()),
(10,N'منوف', 'Menouf',1,GETDATE()),
(10,N'سرس الليان', 'Sars El-Layan',1,GETDATE()),
(10,N'أشمون', 'Ashmon',1,GETDATE()),
(10,N'الباجور', 'Al Bagor',1,GETDATE()),
(10,N'قويسنا', 'Quesna',1,GETDATE()),
(10,N'بركة السبع', 'Berkat El Saba',1,GETDATE()),
(10,N'تلا', 'Tala',1,GETDATE()),
(10,N'الشهداء', 'Al Shohada',1,GETDATE()),
/* Start Monufya ID:10 */

/* Start Minya ID:11 */
(11,N'المنيا', 'Minya',1,GETDATE()),
(11,N'المنيا الجديدة', 'Minya El Gedida',1,GETDATE()),
(11,N'العدوة', 'El Adwa',1,GETDATE()),
(11,N'مغاغة', 'Magagha',1,GETDATE()),
(11,N'بني مزار', 'Bani Mazar',1,GETDATE()),
(11,N'مطاي', 'Mattay',1,GETDATE()),
(11,N'سمالوط', 'Samalut',1,GETDATE()),
(11,N'المدينة الفكرية', 'Madinat El Fekria',1,GETDATE()),
(11,N'ملوي', 'Meloy',1,GETDATE()),
(11,N'دير مواس', 'Deir Mawas',1,GETDATE()),
(11,N'ابو قرقاص', 'Abu Qurqas',1,GETDATE()),
(11,N'ارض سلطان', 'Ard Sultan',1,GETDATE()),
/* End Minya ID:11 */

/* Start Qalubia ID:12 */
(12,N'بنها', 'Banha',1,GETDATE()),
(12,N'قليوب', 'Qalyub',1,GETDATE()),
(12,N'شبرا الخيمة', 'Shubra Al Khaimah',1,GETDATE()),
(12,N'القناطر الخيرية', 'Al Qanater Charity',1,GETDATE()),
(12,N'الخانكة', 'Khanka',1,GETDATE()),
(12,N'كفر شكر', 'Kafr Shukr',1,GETDATE()),
(12,N'طوخ', 'Tukh',1,GETDATE()),
(12,N'قها', 'Qaha',1,GETDATE()),
(12,N'العبور', 'Obour',1,GETDATE()),
(12,N'الخصوص', 'Khosous',1,GETDATE()),
(12,N'شبين القناطر', 'Shibin Al Qanater',1,GETDATE()),
(12,N'مسطرد', 'Mostorod',1,GETDATE()),
/* End Qalubia ID:12 */

/* Start New Valley ID:13 */
(13,N'الخارجة', 'El Kharga',1,GETDATE()),
(13,N'باريس', 'Paris',1,GETDATE()),
(13,N'موط', 'Mout',1,GETDATE()),
(13,N'الفرافرة', 'Farafra',1,GETDATE()),
(13,N'بلاط', 'Balat',1,GETDATE()),
(13,N'الداخلة', 'Dakhla',1,GETDATE()),
/* End New Valley ID:13 */

/* Start South Sinai ID:14 */
(14,N'السويس', 'Suez',1,GETDATE()),
(14,N'الجناين', 'Alganayen',1,GETDATE()),
(14,N'عتاقة', 'Ataqah',1,GETDATE()),
(14,N'العين السخنة', 'Ain Sokhna',1,GETDATE()),
(14,N'فيصل', 'Faysal',1,GETDATE()),
/* End South Sinai ID:14 */

/* Start Aswan ID:15 */
(15,N'أسوان', 'Aswan',1,GETDATE()),
(15,N'أسوان الجديدة', 'Aswan El Gedida',1,GETDATE()),
(15,N'دراو', 'Drau',1,GETDATE()),
(15,N'كوم أمبو', 'Kom Ombo',1,GETDATE()),
(15,N'نصر النوبة', 'Nasr Al Nuba',1,GETDATE()),
(15,N'كلابشة', 'Kalabsha',1,GETDATE()),
(15,N'إدفو', 'Edfu',1,GETDATE()),
(15,N'الرديسية', 'Al-Radisiyah',1,GETDATE()),
(15,N'البصيلية', 'Al Basilia',1,GETDATE()),
(15,N'السباعية', 'Al Sibaeia',1,GETDATE()),
(15,N'ابوسمبل السياحية', 'Abo Simbl Al Siyahia',1,GETDATE()),
(15,N'مرسى علم', 'Marsa Alam',1,GETDATE()),
/* End Aswan ID:15 */

/* Start Assiut ID:16 */
(16,N'أسيوط', 'Assiut',1,GETDATE()),
(16,N'أسيوط الجديدة', 'Assiut El Gedida',1,GETDATE()),
(16,N'ديروط', 'Dayrout',1,GETDATE()),
(16,N'منفلوط', 'Manfalut',1,GETDATE()),
(16,N'القوصية', 'Qusiya',1,GETDATE()),
(16,N'أبنوب', 'Abnoub',1,GETDATE()),
(16,N'أبو تيج', 'Abu Tig',1,GETDATE()),
(16,N'الغنايم', 'El Ghanaim',1,GETDATE()),
(16,N'ساحل سليم', 'Sahel Selim',1,GETDATE()),
(16,N'البداري', 'El Badari',1,GETDATE()),
(16,N'صدفا', 'Sidfa',1,GETDATE()),
/* End Assiut ID:16 */

/* Start Bani Sweif ID:17 */
(17,N'بني سويف', 'Bani Sweif',1,GETDATE()),
(17,N'بني سويف الجديدة', 'Beni Suef El Gedida',1,GETDATE()),
(17,N'الواسطى', 'Al Wasta',1,GETDATE()),
(17,N'ناصر', 'Naser',1,GETDATE()),
(17,N'إهناسيا', 'Ehnasia',1,GETDATE()),
(17,N'ببا', 'beba',1,GETDATE()),
(17,N'الفشن', 'Fashn',1,GETDATE()),
(17,N'سمسطا', 'Somasta',1,GETDATE()),
(17,N'الاباصيرى', 'Alabbaseri',1,GETDATE()),
(17,N'مقبل', 'Mokbel',1,GETDATE()),
/* End Bani Sweif ID:17 */

/* Start PorSaid ID:18 */
(18,N'بورسعيد', 'PorSaid',1,GETDATE()),
(18,N'بورفؤاد', 'Port Fouad',1,GETDATE()),
(18,N'العرب', 'Alarab',1,GETDATE()),
(18,N'حى الزهور', 'Zohour',1,GETDATE()),
(18,N'حى الشرق', 'Alsharq',1,GETDATE()),
(18,N'حى الضواحى', 'Aldawahi',1,GETDATE()),
(18,N'حى المناخ', 'Almanakh',1,GETDATE()),
(18,N'حى مبارك', 'Mubarak',1,GETDATE()),
/* End PorSaid ID:18 */

/* Start Damietta ID:19 */
(19,N'دمياط', 'Damietta',1,GETDATE()),
(19,N'دمياط الجديدة', 'New Damietta',1,GETDATE()),
(19,N'رأس البر', 'Ras El Bar',1,GETDATE()),
(19,N'فارسكور', 'Faraskour',1,GETDATE()),
(19,N'الزرقا', 'Zarqa',1,GETDATE()),
(19,N'السرو', 'alsaru',1,GETDATE()),
(19,N'الروضة', 'alruwda',1,GETDATE()),
(19,N'كفر البطيخ', 'Kafr El-Batikh',1,GETDATE()),
(19,N'عزبة البرج', 'Azbet Al Burg',1,GETDATE()),
(19,N'ميت أبو غالب', 'Meet Abou Ghalib',1,GETDATE()),
(19,N'كفر سعد', 'Kafr Saad',1,GETDATE()),
/* End Damietta ID:19 */

/* Start Sharqia ID:20 */
(20,N'الزقازيق', 'Zagazig',1,GETDATE()),
(20,N'العاشر من رمضان', 'Al Ashr Men Ramadan',1,GETDATE()),
(20,N'منيا القمح', 'Minya Al Qamh',1,GETDATE()),
(20,N'بلبيس', 'Belbeis',1,GETDATE()),
(20,N'مشتول السوق', 'Mashtoul El Souq',1,GETDATE()),
(20,N'القنايات', 'Qenaiat',1,GETDATE()),
(20,N'أبو حماد', 'Abu Hammad',1,GETDATE()),
(20,N'القرين', 'El Qurain',1,GETDATE()),
(20,N'ههيا', 'Hehia',1,GETDATE()),
(20,N'أبو كبير', 'Abu Kabir',1,GETDATE()),
(20,N'فاقوس', 'Faccus',1,GETDATE()),
(20,N'الصالحية الجديدة', 'El Salihia El Gedida',1,GETDATE()),
(20,N'الإبراهيمية', 'Al Ibrahimiyah',1,GETDATE()),
(20,N'ديرب نجم', 'Deirb Negm',1,GETDATE()),
(20,N'كفر صقر', 'Kafr Saqr',1,GETDATE()),
(20,N'أولاد صقر', 'Awlad Saqr',1,GETDATE()),
(20,N'الحسينية', 'Husseiniya',1,GETDATE()),
(20,N'صان الحجر القبلية', 'san alhajar alqablia',1,GETDATE()),
(20,N'منشأة أبو عمر', 'Manshayat Abu Omar',1,GETDATE()),
/* End Sharqia ID:20 */

/* Start South Sinai ID:21 */
(21,N'الطور', 'Al Toor',1,GETDATE()),
(21,N'شرم الشيخ', 'Sharm El-Shaikh',1,GETDATE()),
(21,N'دهب', 'Dahab',1,GETDATE()),
(21,N'نويبع', 'Nuweiba',1,GETDATE()),
(21,N'طابا', 'Taba',1,GETDATE()),
(21,N'سانت كاترين', 'Saint Catherine',1,GETDATE()),
(21,N'أبو رديس', 'Abu Redis',1,GETDATE()),
(21,N'أبو زنيمة', 'Abu Zenaima',1,GETDATE()),
(21,N'رأس سدر', 'Ras Sidr',1,GETDATE()),
/* End South Sinai ID:21 */

/* Start Kafr El Sheikh ID:22 */
(22,N'كفر الشيخ', 'Kafr El Sheikh',1,GETDATE()),
(22,N'وسط البلد كفر الشيخ', 'Kafr El Sheikh Downtown',1,GETDATE()),
(22,N'دسوق', 'Desouq',1,GETDATE()),
(22,N'فوه', 'Fooh',1,GETDATE()),
(22,N'مطوبس', 'Metobas',1,GETDATE()),
(22,N'برج البرلس', 'Burg Al Burullus',1,GETDATE()),
(22,N'بلطيم', 'Baltim',1,GETDATE()),
(22,N'مصيف بلطيم', 'Masief Baltim',1,GETDATE()),
(22,N'الحامول', 'Hamol',1,GETDATE()),
(22,N'بيلا', 'Bella',1,GETDATE()),
(22,N'الرياض', 'Riyadh',1,GETDATE()),
(22,N'سيدي سالم', 'Sidi Salm',1,GETDATE()),
(22,N'قلين', 'Qellen',1,GETDATE()),
(22,N'سيدي غازي', 'Sidi Ghazi',1,GETDATE()),
/* End Kafr El Sheikh ID:22 */

/* Start Matrouh ID:23 */
(23,N'مرسى مطروح', 'Marsa Matrouh',1,GETDATE()),
(23,N'الحمام', 'El Hamam',1,GETDATE()),
(23,N'العلمين', 'Alamein',1,GETDATE()),
(23,N'الضبعة', 'Dabaa',1,GETDATE()),
(23,N'النجيلة', 'Al-Nagila',1,GETDATE()),
(23,N'سيدي براني', 'Sidi Brani',1,GETDATE()),
(23,N'السلوم', 'Salloum',1,GETDATE()),
(23,N'سيوة', 'Siwa',1,GETDATE()),
(23,N'مارينا', 'Marina',1,GETDATE()),
(23,N'الساحل الشمالى', 'North Coast',1,GETDATE()),
/* End Matrouh ID:23 */

/* Start Luxor ID:24 */
(24,N'الأقصر', 'Luxor',1,GETDATE()),
(24,N'الأقصر الجديدة', 'New Luxor',1,GETDATE()),
(24,N'إسنا', 'Esna',1,GETDATE()),
(24,N'طيبة الجديدة', 'New Tiba',1,GETDATE()),
(24,N'الزينية', 'Al ziynia',1,GETDATE()),
(24,N'البياضية', 'Al Bayadieh',1,GETDATE()),
(24,N'القرنة', 'Al Qarna',1,GETDATE()),
(24,N'أرمنت', 'Armant',1,GETDATE()),
(24,N'الطود', 'Al Tud',1,GETDATE()),
/* End Luxor ID:24 */

/* Start Qena ID:25 */
(25,N'قنا', 'Qena',1,GETDATE()),
(25,N'قنا الجديدة', 'New Qena',1,GETDATE()),
(25,N'ابو طشت', 'Abu Tesht',1,GETDATE()),
(25,N'نجع حمادي', 'Nag Hammadi',1,GETDATE()),
(25,N'دشنا', 'Deshna',1,GETDATE()),
(25,N'الوقف', 'Alwaqf',1,GETDATE()),
(25,N'قفط', 'Qaft',1,GETDATE()),
(25,N'نقادة', 'Naqada',1,GETDATE()),
(25,N'فرشوط', 'Farshout',1,GETDATE()),
(25,N'قوص', 'Quos',1,GETDATE()),
/* End Qena ID:25 */

/* Start North Sinai ID:26 */
(26,N'العريش', 'Arish',1,GETDATE()),
(26,N'الشيخ زويد', 'Sheikh Zowaid',1,GETDATE()),
(26,N'نخل', 'Nakhl',1,GETDATE()),
(26,N'رفح', 'Rafah',1,GETDATE()),
(26,N'بئر العبد', 'Bir al-Abed',1,GETDATE()),
(26,N'الحسنة', 'Al Hasana',1,GETDATE()),
/* End North Sinai ID:26 */

/* Start Sohag ID:27 */
(27,N'سوهاج', 'Sohag',1,GETDATE()),
(27,N'سوهاج الجديدة', 'Sohag El Gedida',1,GETDATE()),
(27,N'أخميم', 'Akhmeem',1,GETDATE()),
(27,N'أخميم الجديدة', 'Akhmim El Gedida',1,GETDATE()),
(27,N'البلينا', 'Albalina',1,GETDATE()),
(27,N'المراغة', 'El Maragha',1,GETDATE()),
(27,N'المنشأة', 'almunshaa',1,GETDATE()),
(27,N'دار السلام', 'Dar AISalaam',1,GETDATE()),
(27,N'جرجا', 'Gerga',1,GETDATE()),
(27,N'جهينة الغربية', 'Jahina Al Gharbia',1,GETDATE()),
(27,N'ساقلته', 'Saqilatuh',1,GETDATE()),
(27,N'طما', 'Tama',1,GETDATE()),
(27,N'طهطا', 'Tahta',1,GETDATE()),
(27,N'الكوثر', 'Alkawthar',1,GETDATE());